ptx:
  siim_acr:
    root_dir: "/path/to/your/datasets"
  vindr:
      root_dir: "/path/to/your/datasets"
  ptx498:
      root_dir: "/path/to/your/datasets"
  model:
      checkpoint_dir: "/path/to/your/checkpoints"  # Where to save model checkpoints
      tuned_checkpoint_dir: "/path/to/your/checkpoints"  # Optional, you only need this if you want to compare cross validation with standard parameters vs tuned parameters
pneumonia:
  rsna_pneumonia:
    root_dir: "/path/to/your/datasets"
  siim_covid:
      root_dir: "/path/to/your/datasets"
  model:
      checkpoint_dir: "/path/to/your/checkpoints"  # Where to save model checkpoints
      tuned_checkpoint_dir: "/path/to/your/checkpoints"  # Optional, you only need this if you want to compare cross validation with standard parameters vs tuned parameters